import pic1 from "./PG/pic1.png";
import pic2 from "./PG/pic2.png";
import pic3 from "./PG/pic3.png";
import pic4 from "./PG/pic4.png";
import gry_start from "./images/5_ry_start.png";
import offer from "./images/10_Off.png";
import new_tag from "./images/New_lable.png";
import cart from "./images/cart.svg";

export const shoeary = [
  {
    img1: pic1 ,
    img2: "offer",
    img3: "new_tag",
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic2 ,
    img2: "offer",
    img3: "new_tag",
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic3,
    img2: "offer",
    img3: "cd fronend",
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img: pic4,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic1,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img: pic2,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic1,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img: pic2,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic1,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img: pic2,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic1,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img: pic2,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: pic1,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img: pic2,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
];
